### Iris dataset classification

This is one of a few notebooks designed to showcase how Conveyor can make your work in Jupyter more organized. The objective of this example is to seperate the Iris dataset classification task (covered [here](https://scikit-learn.org/stable/tutorial/statistical_inference/supervised_learning.html)) into smaller subtasks, from exploratory data analysis to evaluating different classification strategies.

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris_X, iris_y = datasets.load_iris(return_X_y=True)

(From scikit-learn's website) "The iris dataset is a classification task consisting in identifying 3 different types of irises (Setosa, Versicolour, and Virginica) from their petal and sepal length and width."

In [3]:
np.unique(iris_y)

array([0, 1, 2])

In [8]:
# iris_X appears to contain petal and sepal lengths and widths...
iris_X[0]

array([5.1, 3.5, 1.4, 0.2])

In [9]:
# The 0 class is a type of flower
iris_y[0]

0

How many of each type of flower does the dataset contain?

In [20]:
class_count = [0]*len(np.unique(iris_y))

for flower_type in iris_y:
    class_count[flower_type] += 1

class_count

[50, 50, 50]

Are there any obvious identifying characteristics about each flower's petals? What about sepal and petal areas?

In [33]:
class_data = [iris_X[np.where(iris_y == flower_type)] for flower_type in np.unique(iris_y)]
class_areas_avg = []
class_areas = []

for flower_type in range(len(class_data)):
    flower_avg_dims = np.mean(class_data[flower_type], axis=1) 
    class_areas_avg.append((flower_avg_dims[0]*flower_avg_dims[1],
                        flower_avg_dims[2]*flower_avg_dims[3]))
    class_areas.append([(x[0]*x[1], x[2]*x[3]) for x in class_data[flower_type]])
    
# From classes 0 to 1 to 2 the average sizes increase
class_areas_avg

[(6.0562499999999995, 5.522499999999999),
 (15.892499999999998, 13.4275),
 (17.534375, 18.77875)]

The average areas seem to be markedly different among the three types of flowers. Do the areas vary much across individual flowers, relative to these values? If so, area will not be a useful indicator for classifying our flowers.

In [36]:
np.var(class_areas, axis=1)

array([[ 8.43489316,  0.03216064],
       [ 8.05463156,  1.83507584],
       [11.72391684,  4.56133956]])

Petal area doesn't seem to vary too much. In the next notebook, I'll try classifying each flower using the sepal and petal areas.

In [37]:
iris_X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3